import SideNavBar from "@/Components/SideBar/SideNavBar";
import "./globals.css";
import Footer from "@/Components/Footer/Footer";
import Providers from "./redux/Provider";

// import logo from "./../../public/assets/logo2.jpg";

export const metadata = {
  title: 'Afzal_Porfolio',
  description: 'Generated by Next.js',
  icons: {
    shortcut: [
      '/logo2.jpg'
    ]
  },
  manifest: '/site-webmanifext'
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body>
        <Providers>
          <div className="w-full flex m-0 p-0 scroll-smooth">
            <SideNavBar />
            <div className="w-full flex flex-col scroll-smooth">
              {children}
              <Footer />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  )
}
