import SideNavBar from "@/Components/SideBar/SideNavBar";
import "./globals.css";
import Footer from "@/Components/Footer/Footer";
import Providers from "./redux/Provider";
import Head from "next/head";
// import logo from "./../../public/assets/logo2.jpg";

export const metadata = {
  title: 'Afzal_Porfolio',
  description: 'Generated by Next.js',
  icons: {
    shortcut: [
      '/logo2.jpg'
    ]
  },
  manifest: '/site-webmanifext'
}

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        {/* Add a link to your favicon file */}
        <link
          rel="icon"
          href="/assets/logo2.jpg"
          type="image/jpg"

        />
      </Head>
      <html lang="en">
        <body>
          <Providers>
            <div className="w-full flex m-0 p-0 scroll-smooth">
              <SideNavBar />
              <div className="w-full flex flex-col scroll-smooth">
                {children}
                <Footer />
              </div>
            </div>
          </Providers>
        </body>
      </html>
    </>
  )
}
